kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: secretclaims.vaultproject.io
description: Vault managed secret claim.
spec:
  version: v1
  group: vaultproject.io
  scope: Namespaced
  names:
    plural: secretclaims
    singular: secretclaim
    kind: SecretClaim
    shortNames:
    - scl
